image: Visual Studio 2019

branches:
  only:
    - main

cache:
  - node_modules -> package.json

environment:
  nodejs_version: "18"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq 'true') {
        Push-AppveyorArtifact "dist" -DeploymentName "GitHubPages"
      }
