image: Visual Studio 2019

branches:
  only:
    - main

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node 14
  - npm install

build_script:
  - npm run build

deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq 'true') {
        Push-AppveyorArtifact "dist" -DeploymentName "GitHubPages"
      }
